{% set name = "medpy" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/medpy-{{ version }}.tar.gz
  sha256: f4233c2f4adc79abe4b8ff5b683ba4778322d4545e71d51d6a328ad31275972d
  patches:
  - graphcut_boost_lib.patch
  - fix-compile.patch

build:
  number: 2
  skip: true  # [win and py==38]
  script:
    - export LDFLAGS="${LDFLAGS} -L${PREFIX}/lib"                                            # [unix]
    - export CXXFLAGS="${CXXFLAGS} -I${PREFIX}/include -I${PYTHON_INCLUDE_DIR}"              # [unix]
    # see https://github.com/boostorg/system/issues/32#issuecomment-462912013
    - set "CXXFLAGS=%CXXFLAGS% /DHAVE_SNPRINTF=1"                                            # [win]
    - set "CFLAGS=%CFLAGS% /DHAVE_SNPRINTF=1"                                                # [win]
    - python setup.py build_ext --include-dirs=%PREFIX%\include --library-dirs=%PREFIX%\lib  # [win]
    - python setup.py build_ext --include-dirs=$PREFIX/include --library-dirs=$PREFIX/lib    # [not win]
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - setuptools
  host:
    - libboost-python-devel
    - pip
    - python
  run:
    - numpy >=1.24
    - python
    - simpleitk >=2.1
    - scipy >=1.10
    - setuptools

test:
  imports:
    - medpy
    - medpy.core
    - medpy.features
    - medpy.filter
    - medpy.graphcut
    - medpy.io
    - medpy.iterators
    - medpy.metric
    - medpy.neighbours
    - medpy.utilities
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/loli/medpy
  summary: Medical image processing in Python
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  doc_url: http://loli.github.io/medpy/
  dev_url: http://loli.github.io/medpy/installation/developmentmode.html

extra:
  recipe-maintainers:
    - sarthakpati
    - loli
